### ISSUE TITLE
Add an instruction to download submodules somewhere....

### ISSUE THREAD

**Issue by rojas70** [wsnewman/learning_ros_external_pkgs_noetic#2]
To download catkin_simple, sticky_fingers, and gazebo_ros_packages, need to add:
````
git submodule update --init --recursive
````
to download these... maybe in the scripts?

**Comment by frank-qcd-qk** [comment]
This should be addressable by doing `git clone -r xxxxxxxx` to directly recursively pull. Since the version is pinned and students do are not expected to work on the external packages it sshould be fine. Introducing the git submodule involves introducing them a bunch of new concepts.

**Comment by rojas70** [comment]
I see easy to miss. Should highlight it somewhere as it is not the default way of calling clone.
